const API_BASE_URL = "http://localhost:5123";
const API_CURRENTS_ENDPOINT = "/currentss";
const API_COMPLETED_ENDPOINT = "/completed";
const DEFAULT_TIMEOUT = 5000;

export {
  API_BASE_URL,
  API_CURRENTS_ENDPOINT,
  API_COMPLETED_ENDPOINT,
  DEFAULT_TIMEOUT,
};
